# Generated by Django 5.1.1 on 2025-03-28 01:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True)),
                ('category_code', models.CharField(help_text='Mã danh mục (2 ký tự, ví dụ: CA)', max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_ocr.category')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='invoice_ocr.product')),
                ('quantity_in_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_ocr.supplier'),
        ),
        migrations.CreateModel(
            name='WarehouseReceipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('receipt_date', models.DateField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_ocr.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('note', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_ocr.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_ocr.warehousereceipt')),
            ],
        ),
    ]
