# Generated by Django 5.1.1 on 2025-05-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_ocr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên mẫu hóa đơn')),
                ('template_image', models.ImageField(upload_to='invoice_templates/', verbose_name='Ảnh mẫu hóa đơn')),
                ('supplier_code_keywords', models.TextField(help_text='Các từ khóa cách nhau bằng dấu phẩy (,)', verbose_name='Từ khóa nhận dạng mã nhà cung cấp')),
                ('invoice_number_keywords', models.TextField(help_text='Các từ khóa cách nhau bằng dấu phẩy (,)', verbose_name='Từ khóa nhận dạng số hóa đơn/đơn hàng')),
                ('product_code_keywords', models.TextField(help_text='Các từ khóa cách nhau bằng dấu phẩy (,)', verbose_name='Từ khóa nhận dạng cột mã hàng')),
                ('quantity_keywords', models.TextField(help_text='Các từ khóa cách nhau bằng dấu phẩy (,)', verbose_name='Từ khóa nhận dạng cột số lượng')),
                ('num_columns', models.PositiveIntegerField(default=0, verbose_name='Số cột trong bảng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
