# Generated by Django 5.1.1 on 2025-03-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('invoice_ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='receiptdetail',
            unique_together={('receipt', 'product')},
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='useraccount_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='useraccount_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
