# Generated by Django 5.1.1 on 2025-05-14 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_ocr', '0002_invoicetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousereceipt',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL),
        ),
    ]
